# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes

wedstrijdverslagen:
    name: Wedstrijdverslagen
    singular_name: Wedstrijdverslag
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: [season,team_id,title]
        date:
            type: date
        auteur:
            type: select
            label: Auteur
            values: [ "", "Give & Go", "Ed Nawijn", "Karin Mateman", "Bestuur", "Edward Jansen", "Tom Eugelink", "Richard Hinkamp", "Bart Demkes", "Frank Hakstege", "Foeke Wybrandi", "Marleen Scholten", "Igor Hoogakker", "Marca Adema" ]
        team_id:
            type: select
            label: Team
            values: [ X16, M18, V22, U10, U12, U14, U16, U16M, U18, U18M, U20M, U20, D1, H1, H2, RC ]
        season:
            type: text
            default: "2018-2019"
            class: narrow
            variant: inline
        teaser:
            type: textarea
        body:
            type: html
            height: 300px
    record_template: wedstrijdverslagen-detail.twig
    listing_template: layout/news-list.twig
    listing_records: 10
    sort: date DESC
    recordsperpage: 10
    default_status: publish
    rss:
      enabled: true
      feed_records: 10
      feed_template: rss.twig
      content_length: 250

mededelingen:
    name: Mededelingen
    singular_name: Mededeling
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        date:
            type: date
        auteur:
            type: select
            label: Auteur
            values: [ "Give & Go", "" ]
        teaser:
            type: textarea
        body:
            type: html
            height: 300px
        old_id:
            type: integer
    record_template: mededelingen-detail.twig
    listing_template: layout/news-list.twig
    listing_records: 10
    sort: date DESC
    recordsperpage: 10
    default_status: publish
    rss:
      enabled: true
      feed_records: 10
      feed_template: rss.twig
      content_length: 250

paginas:
    name: Paginas
    singular_name: Pagina
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        introduction:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        menu:
            type: select
            label: In menu?
            values: [ Nee, Ja ]
        menu_name:
            type: text
            class: large
            label: Naam in menu
        menu_order:
            type: integer
            label: Menu sortering
        template:
            type: templateselect
            filter: 'page-*.twig'
    sort: title
    recordsperpage: 100
    record_template: page.twig
    default_status: publish

teams:
    name: Teams
    singular_name: Team
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        introduction:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        team_id:
            type: select
            label: Team
            values: [ X16, M18, V22, U10, U12, U14, U16, U16M, U18, U18M, U20M, U20, D1, H1, H2, RC ]
        nbb_competitie_id:
            type: integer
            label: NBB Competitie ID
        nbb_team_id:
            type: integer
            label: NBB Team ID
        menu_order:
            type: integer
            label: Menu sortering
    taxonomy: [ teams ]
    sort: menu_order
    record_template: team-detail.twig
    listing_template: team-list.twig
    listing_records: 100
    recordsperpage: 100
    default_status: publish

scores:
    name: Scores
    singular_name: Score
    show_on_dashboard: false
    show_in_menu: false
    fields:
        team_id:
            type: select
            label: Team
            values: [ X16, M18, V22, U10, U12, U14, U16, U16M, U18, U18M, U20M, U20, D1, H1, H2, RC ]
        season:
            type: select
            label: Seizoen
            values: [ 2012-2013, 2013-2014, 2014-2015, 2015-2016, 2016-2017, 2017-2018, 2018-2019 ]
        datetime:
            type: datetime
            label: Datum + tijd
        team_home:
            type: text
            label: Naam thuis team
        team_away:
            type: text
            label: Naam uit team
        score_home:
            type: integer
            label: Score thuis team
        score_away:
            type: integer
            label: Score uit team
    sort: datetime DESC

standings:
    name: Standings
    singular_name: Standing
    show_on_dashboard: false
    show_in_menu: false
    fields:
        team_id:
            type: select
            label: Team
            values: [ X16, M18, V22, U10, U12, U14, U16, U16M, U18, U18M, U20M, U20, D1, H1, H2, RC ]
        season:
            type: select
            label: Seizoen
            values: [ 2012-2013, 2013-2014, 2014-2015, 2015-2016, 2016-2017, 2017-2018, 2018-2019 ]
        place:
            type: integer
            label: Plek
        team_name:
            type: text
            label: Naam team
        played:
            type: integer
            label: Gespeelde wedstrijden
        points:
            type: integer
            label: Punten
        goal_difference:
            type: integer
            label: Doelsaldo
        goals_scored:
            type: integer
            label: Scores voor
        goals_allowed:
            type: integer
            label: Scores tegen
        win_percentage:
            type: float
            label: Winst percentage
    sort: place

picasa_album:
    name: Foto albums
    slug: foto-albums
    singular_name: Foto album
    singular_slug: foto-album
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        description:
            type: textarea
            height: 150px
        url:
            type: text
        thumb_url:
            type: text
        sync:
            type: checkbox
    sort: datepublish DESC
    record_template: picasa-detail.twig
    listing_template: picasa-listing.twig
    default_status: draft

picasa_photo:
    name: Foto's
    slug: fotos
    singular_name: Foto
    singular_slug: foto
    show_on_dashboard: false
    show_in_menu: false
    fields:
        album_id:
            type: integer
        title:
            type: text
            class: large
        url:
            type: text
        thumb_url:
            type: text
    sort: datepublish ASC
    default_status: published

# possible field types:
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# templateselect - varchar(256) - select with template filenames


# number (deprecated) - input type decimal(18,9), useful for storing number that need to be sortable
